# do not touch this line
configVersion: 2

name: MatrixInfoApp
description: This app shows informations about all sensor on app dashboard
keywords: 'sensor, info, dash'

screens:
  - - sensorDetails
  - - gyroscopeDetails
  - - uvDetails

sensors:
  - temperature
  - humidity
  - gyroscope
  - uv
  - pressure
  - altitude

dataTypes:
  sensorValue:
    TypeSensor: string
    Value: float
  gyroscopeValue:
    Pitch: float
    Roll: float
    Yaw: float
  uvValue:
    Risk: string
    Percentage: float

widgets:
  sensorDetails:
    type: sensorValue
    display: list-group
    groupBy: sensorName
    label: Sensor's details
    keys:
      - TypeSensor
      - Value
  gyroscopeDetails:
    type: gyroscopeValue
    display: list-group
    label: Gyroscope axis
    keys:
      - Pitch
      - Roll
      - Yaw
  uvDetails:
    type: uvValue
    display: list-group
    label: UV risk details
    keys:
      - Risk
      - Percentage
