# do not touch this line
configVersion: 2

name: filterTest
description: >-
  this is a app test for filtering all the sensor, and showing some log messages
  if some conditions are true
keywords: filter sensors

dataTypes:
  temperature: float


sensors:
  - temperature

dataTypes:
  temperature: float
